/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Azaelmglw
 */
public class ViewPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form ViewPeliculas
     */
    public ViewPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_encabezado = new javax.swing.JLabel();
        jlb_id = new javax.swing.JLabel();
        jlb_nombre = new javax.swing.JLabel();
        jlb_formato = new javax.swing.JLabel();
        jlb_duracion = new javax.swing.JLabel();
        jlb_descripcion = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_duracion = new javax.swing.JTextField();
        jcb_formato = new javax.swing.JComboBox<>();
        jsp_area_trabajo = new javax.swing.JScrollPane();
        jta_descripcion = new javax.swing.JTextArea();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_almacenar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setPreferredSize(new java.awt.Dimension(1024, 600));

        jlb_encabezado.setFont(new java.awt.Font("PakType Naskh Basic", 1, 36)); // NOI18N
        jlb_encabezado.setForeground(new java.awt.Color(204, 204, 204));
        jlb_encabezado.setText("Películas");

        jlb_id.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_id.setForeground(new java.awt.Color(204, 204, 204));
        jlb_id.setText("ID:");
        jlb_id.setMaximumSize(new java.awt.Dimension(100, 34));
        jlb_id.setMinimumSize(new java.awt.Dimension(100, 34));
        jlb_id.setPreferredSize(new java.awt.Dimension(100, 34));

        jlb_nombre.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_nombre.setForeground(new java.awt.Color(204, 204, 204));
        jlb_nombre.setText("Nombre:");
        jlb_nombre.setMaximumSize(new java.awt.Dimension(100, 34));
        jlb_nombre.setMinimumSize(new java.awt.Dimension(100, 34));
        jlb_nombre.setPreferredSize(new java.awt.Dimension(100, 34));

        jlb_formato.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_formato.setForeground(new java.awt.Color(204, 204, 204));
        jlb_formato.setText("Formato:");
        jlb_formato.setMaximumSize(new java.awt.Dimension(100, 34));
        jlb_formato.setMinimumSize(new java.awt.Dimension(100, 34));
        jlb_formato.setPreferredSize(new java.awt.Dimension(100, 34));

        jlb_duracion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_duracion.setForeground(new java.awt.Color(204, 204, 204));
        jlb_duracion.setText("Duración:");
        jlb_duracion.setMaximumSize(new java.awt.Dimension(100, 34));
        jlb_duracion.setMinimumSize(new java.awt.Dimension(100, 34));
        jlb_duracion.setPreferredSize(new java.awt.Dimension(100, 34));

        jlb_descripcion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_descripcion.setForeground(new java.awt.Color(204, 204, 204));
        jlb_descripcion.setText("Descripción:");
        jlb_descripcion.setMaximumSize(new java.awt.Dimension(140, 34));
        jlb_descripcion.setMinimumSize(new java.awt.Dimension(140, 34));
        jlb_descripcion.setPreferredSize(new java.awt.Dimension(140, 34));

        jtf_id.setBackground(new java.awt.Color(102, 102, 102));
        jtf_id.setFont(new java.awt.Font("PakType Naskh Basic", 1, 20)); // NOI18N
        jtf_id.setForeground(new java.awt.Color(255, 255, 255));
        jtf_id.setMaximumSize(new java.awt.Dimension(200, 40));
        jtf_id.setMinimumSize(new java.awt.Dimension(200, 40));
        jtf_id.setPreferredSize(new java.awt.Dimension(200, 40));

        jtf_nombre.setBackground(new java.awt.Color(102, 102, 102));
        jtf_nombre.setFont(new java.awt.Font("PakType Naskh Basic", 1, 20)); // NOI18N
        jtf_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jtf_nombre.setMaximumSize(new java.awt.Dimension(200, 40));
        jtf_nombre.setMinimumSize(new java.awt.Dimension(200, 40));
        jtf_nombre.setPreferredSize(new java.awt.Dimension(200, 40));

        jtf_duracion.setBackground(new java.awt.Color(102, 102, 102));
        jtf_duracion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 20)); // NOI18N
        jtf_duracion.setForeground(new java.awt.Color(255, 255, 255));
        jtf_duracion.setMaximumSize(new java.awt.Dimension(200, 40));
        jtf_duracion.setMinimumSize(new java.awt.Dimension(200, 40));
        jtf_duracion.setPreferredSize(new java.awt.Dimension(200, 40));

        jcb_formato.setBackground(new java.awt.Color(102, 102, 102));
        jcb_formato.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jcb_formato.setForeground(new java.awt.Color(255, 255, 255));
        jcb_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DVD", "Blu-ray" }));
        jcb_formato.setAlignmentX(0.0F);
        jcb_formato.setAlignmentY(0.0F);
        jcb_formato.setDoubleBuffered(true);
        jcb_formato.setMaximumSize(new java.awt.Dimension(200, 40));
        jcb_formato.setMinimumSize(new java.awt.Dimension(200, 40));
        jcb_formato.setPreferredSize(new java.awt.Dimension(200, 40));

        jta_descripcion.setBackground(new java.awt.Color(51, 51, 51));
        jta_descripcion.setColumns(10);
        jta_descripcion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jta_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        jta_descripcion.setLineWrap(true);
        jta_descripcion.setRows(5);
        jta_descripcion.setMaximumSize(new java.awt.Dimension(307, 204));
        jta_descripcion.setMinimumSize(new java.awt.Dimension(307, 204));
        jsp_area_trabajo.setViewportView(jta_descripcion);

        jbtn_primero.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_primero.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_primero.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_primero.setText("|<");
        jbtn_primero.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_primero.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_primero.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_anterior.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_anterior.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_anterior.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_anterior.setText("Anterior");
        jbtn_anterior.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_siguiente.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_siguiente.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_siguiente.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_siguiente.setText("Siguiente");
        jbtn_siguiente.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_siguiente.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_siguiente.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_ultimo.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_ultimo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_ultimo.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_ultimo.setText(">|");
        jbtn_ultimo.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_ultimo.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_ultimo.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_almacenar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_almacenar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_almacenar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_almacenar.setText("Almacenar");
        jbtn_almacenar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_almacenar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_almacenar.setPreferredSize(new java.awt.Dimension(300, 40));

        jbtn_modificar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_modificar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_modificar.setText("Modificar");
        jbtn_modificar.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_modificar.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_modificar.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_eliminar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_eliminar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setPreferredSize(new java.awt.Dimension(300, 40));

        jbtn_nuevo.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_nuevo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_nuevo.setText("Nuevo");
        jbtn_nuevo.setMaximumSize(new java.awt.Dimension(884, 40));
        jbtn_nuevo.setMinimumSize(new java.awt.Dimension(884, 40));
        jbtn_nuevo.setPreferredSize(new java.awt.Dimension(884, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jlb_encabezado))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jcb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp_area_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jbtn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlb_encabezado)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jlb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jsp_area_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlb_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_almacenar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JComboBox<String> jcb_formato;
    public javax.swing.JLabel jlb_descripcion;
    public javax.swing.JLabel jlb_duracion;
    public javax.swing.JLabel jlb_encabezado;
    public javax.swing.JLabel jlb_formato;
    public javax.swing.JLabel jlb_id;
    public javax.swing.JLabel jlb_nombre;
    public javax.swing.JScrollPane jsp_area_trabajo;
    public javax.swing.JTextArea jta_descripcion;
    public javax.swing.JTextField jtf_duracion;
    public javax.swing.JTextField jtf_id;
    public javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
