/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Azaelmglw
 */
public class ViewRentas extends javax.swing.JPanel {

    /**
     * Creates new form ViewPeliculas
     */
    public ViewRentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_encabezado = new javax.swing.JLabel();
        jlb_cliente = new javax.swing.JLabel();
        jlb_pelicula = new javax.swing.JLabel();
        jlb_dias = new javax.swing.JLabel();
        jcb_cliente = new javax.swing.JComboBox<>();
        jcb_pelicula = new javax.swing.JComboBox<>();
        jspn_dias = new javax.swing.JSpinner();
        jsp_tabla_rentas = new javax.swing.JScrollPane();
        jtb_tabla_rentas = new javax.swing.JTable();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_almacenar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setPreferredSize(new java.awt.Dimension(1024, 600));

        jlb_encabezado.setFont(new java.awt.Font("PakType Naskh Basic", 1, 36)); // NOI18N
        jlb_encabezado.setForeground(new java.awt.Color(204, 204, 204));
        jlb_encabezado.setText("Rentas");

        jlb_cliente.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_cliente.setForeground(new java.awt.Color(204, 204, 204));
        jlb_cliente.setText("Cliente:");
        jlb_cliente.setMaximumSize(new java.awt.Dimension(100, 34));
        jlb_cliente.setMinimumSize(new java.awt.Dimension(100, 34));
        jlb_cliente.setPreferredSize(new java.awt.Dimension(100, 34));

        jlb_pelicula.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_pelicula.setForeground(new java.awt.Color(204, 204, 204));
        jlb_pelicula.setText("Película:");
        jlb_pelicula.setMaximumSize(new java.awt.Dimension(100, 34));
        jlb_pelicula.setMinimumSize(new java.awt.Dimension(100, 34));
        jlb_pelicula.setPreferredSize(new java.awt.Dimension(100, 34));

        jlb_dias.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_dias.setForeground(new java.awt.Color(204, 204, 204));
        jlb_dias.setText("No. Días:");
        jlb_dias.setMaximumSize(new java.awt.Dimension(100, 34));
        jlb_dias.setMinimumSize(new java.awt.Dimension(100, 34));
        jlb_dias.setPreferredSize(new java.awt.Dimension(100, 34));

        jcb_cliente.setBackground(new java.awt.Color(102, 102, 102));
        jcb_cliente.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jcb_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jcb_cliente.setMaximumSize(new java.awt.Dimension(200, 40));
        jcb_cliente.setMinimumSize(new java.awt.Dimension(200, 40));
        jcb_cliente.setPreferredSize(new java.awt.Dimension(200, 40));
        jcb_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_clienteActionPerformed(evt);
            }
        });

        jcb_pelicula.setBackground(new java.awt.Color(102, 102, 102));
        jcb_pelicula.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jcb_pelicula.setForeground(new java.awt.Color(255, 255, 255));
        jcb_pelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        jcb_pelicula.setMaximumSize(new java.awt.Dimension(200, 40));
        jcb_pelicula.setMinimumSize(new java.awt.Dimension(200, 40));
        jcb_pelicula.setPreferredSize(new java.awt.Dimension(200, 40));
        jcb_pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_peliculaActionPerformed(evt);
            }
        });

        jspn_dias.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jspn_dias.setMaximumSize(new java.awt.Dimension(128, 40));
        jspn_dias.setMinimumSize(new java.awt.Dimension(128, 40));
        jspn_dias.setPreferredSize(new java.awt.Dimension(128, 40));

        jsp_tabla_rentas.setBackground(new java.awt.Color(51, 51, 51));

        jtb_tabla_rentas.setBackground(new java.awt.Color(153, 153, 153));
        jtb_tabla_rentas.setForeground(new java.awt.Color(0, 0, 0));
        jtb_tabla_rentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtb_tabla_rentas.setRowHeight(20);
        jsp_tabla_rentas.setViewportView(jtb_tabla_rentas);

        jbtn_modificar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_modificar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_modificar.setText("Modificar");
        jbtn_modificar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_modificar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_modificar.setPreferredSize(new java.awt.Dimension(300, 40));

        jbtn_eliminar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_eliminar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setPreferredSize(new java.awt.Dimension(300, 40));

        jbtn_almacenar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_almacenar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_almacenar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_almacenar.setText("Almacenar");
        jbtn_almacenar.setMaximumSize(new java.awt.Dimension(882, 40));
        jbtn_almacenar.setMinimumSize(new java.awt.Dimension(882, 40));
        jbtn_almacenar.setPreferredSize(new java.awt.Dimension(882, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlb_encabezado)
                .addGap(850, 850, 850))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspn_dias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jsp_tabla_rentas)
                    .addComponent(jbtn_almacenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(454, 454, 454))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_encabezado)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlb_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jspn_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlb_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcb_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addComponent(jsp_tabla_rentas, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_clienteActionPerformed

    private void jcb_peliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_peliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_peliculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_almacenar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JComboBox<String> jcb_cliente;
    public javax.swing.JComboBox<String> jcb_pelicula;
    public javax.swing.JLabel jlb_cliente;
    public javax.swing.JLabel jlb_dias;
    public javax.swing.JLabel jlb_encabezado;
    public javax.swing.JLabel jlb_pelicula;
    public javax.swing.JScrollPane jsp_tabla_rentas;
    public javax.swing.JSpinner jspn_dias;
    public javax.swing.JTable jtb_tabla_rentas;
    // End of variables declaration//GEN-END:variables
}
