/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Azaelmglw
 */
public class ViewClientes extends javax.swing.JPanel {

    /**
     * Creates new form ViewClientes
     */
    public ViewClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_encabezado = new javax.swing.JLabel();
        jlb_id = new javax.swing.JLabel();
        jlb_nombre = new javax.swing.JLabel();
        jlb_telefono = new javax.swing.JLabel();
        jlb_email = new javax.swing.JLabel();
        jlb_direccion = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jtf_email = new javax.swing.JTextField();
        jtf_direccion = new javax.swing.JTextField();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_almacenar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));

        jlb_encabezado.setFont(new java.awt.Font("PakType Naskh Basic", 1, 36)); // NOI18N
        jlb_encabezado.setForeground(new java.awt.Color(204, 204, 204));
        jlb_encabezado.setText("Clientes");

        jlb_id.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_id.setForeground(new java.awt.Color(204, 204, 204));
        jlb_id.setText("ID:");
        jlb_id.setMaximumSize(new java.awt.Dimension(110, 34));
        jlb_id.setMinimumSize(new java.awt.Dimension(110, 34));
        jlb_id.setPreferredSize(new java.awt.Dimension(110, 34));

        jlb_nombre.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_nombre.setForeground(new java.awt.Color(204, 204, 204));
        jlb_nombre.setText("Nombre:");
        jlb_nombre.setMaximumSize(new java.awt.Dimension(110, 34));
        jlb_nombre.setMinimumSize(new java.awt.Dimension(110, 34));
        jlb_nombre.setPreferredSize(new java.awt.Dimension(110, 34));

        jlb_telefono.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_telefono.setForeground(new java.awt.Color(204, 204, 204));
        jlb_telefono.setText("Teléfono:");
        jlb_telefono.setMaximumSize(new java.awt.Dimension(110, 34));
        jlb_telefono.setMinimumSize(new java.awt.Dimension(110, 34));
        jlb_telefono.setPreferredSize(new java.awt.Dimension(110, 34));

        jlb_email.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_email.setForeground(new java.awt.Color(204, 204, 204));
        jlb_email.setText("Email:");
        jlb_email.setMaximumSize(new java.awt.Dimension(110, 34));
        jlb_email.setMinimumSize(new java.awt.Dimension(110, 34));
        jlb_email.setPreferredSize(new java.awt.Dimension(110, 34));

        jlb_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jlb_direccion.setForeground(new java.awt.Color(204, 204, 204));
        jlb_direccion.setText("Dirección:");
        jlb_direccion.setMaximumSize(new java.awt.Dimension(110, 34));
        jlb_direccion.setMinimumSize(new java.awt.Dimension(110, 34));
        jlb_direccion.setPreferredSize(new java.awt.Dimension(110, 34));

        jtf_id.setBackground(new java.awt.Color(102, 102, 102));
        jtf_id.setFont(new java.awt.Font("PakType Naskh Basic", 1, 20)); // NOI18N
        jtf_id.setForeground(new java.awt.Color(255, 255, 255));
        jtf_id.setMaximumSize(new java.awt.Dimension(300, 40));
        jtf_id.setMinimumSize(new java.awt.Dimension(300, 40));
        jtf_id.setPreferredSize(new java.awt.Dimension(300, 40));

        jtf_nombre.setBackground(new java.awt.Color(102, 102, 102));
        jtf_nombre.setFont(new java.awt.Font("PakType Naskh Basic", 1, 20)); // NOI18N
        jtf_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jtf_nombre.setMaximumSize(new java.awt.Dimension(300, 40));
        jtf_nombre.setMinimumSize(new java.awt.Dimension(300, 40));
        jtf_nombre.setName(""); // NOI18N
        jtf_nombre.setPreferredSize(new java.awt.Dimension(300, 40));

        jtf_telefono.setBackground(new java.awt.Color(102, 102, 102));
        jtf_telefono.setFont(new java.awt.Font("PakType Naskh Basic", 1, 20)); // NOI18N
        jtf_telefono.setForeground(new java.awt.Color(255, 255, 255));
        jtf_telefono.setMaximumSize(new java.awt.Dimension(300, 40));
        jtf_telefono.setMinimumSize(new java.awt.Dimension(300, 40));
        jtf_telefono.setName(""); // NOI18N
        jtf_telefono.setPreferredSize(new java.awt.Dimension(300, 40));

        jtf_email.setBackground(new java.awt.Color(102, 102, 102));
        jtf_email.setFont(new java.awt.Font("PakType Naskh Basic", 1, 20)); // NOI18N
        jtf_email.setForeground(new java.awt.Color(255, 255, 255));
        jtf_email.setMaximumSize(new java.awt.Dimension(300, 40));
        jtf_email.setMinimumSize(new java.awt.Dimension(300, 40));
        jtf_email.setName(""); // NOI18N
        jtf_email.setPreferredSize(new java.awt.Dimension(300, 40));

        jtf_direccion.setBackground(new java.awt.Color(102, 102, 102));
        jtf_direccion.setFont(new java.awt.Font("PakType Naskh Basic", 1, 20)); // NOI18N
        jtf_direccion.setForeground(new java.awt.Color(255, 255, 255));
        jtf_direccion.setMaximumSize(new java.awt.Dimension(300, 40));
        jtf_direccion.setMinimumSize(new java.awt.Dimension(300, 40));
        jtf_direccion.setName(""); // NOI18N
        jtf_direccion.setPreferredSize(new java.awt.Dimension(300, 40));

        jbtn_primero.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_primero.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_primero.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_primero.setText("|<");
        jbtn_primero.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_primero.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_primero.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_anterior.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_anterior.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_anterior.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_anterior.setText("Anterior");
        jbtn_anterior.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_anterior.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_siguiente.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_siguiente.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_siguiente.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_siguiente.setText("Siguiente");
        jbtn_siguiente.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_siguiente.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_siguiente.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_ultimo.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_ultimo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_ultimo.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_ultimo.setText(">|");
        jbtn_ultimo.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_ultimo.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_ultimo.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_almacenar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_almacenar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_almacenar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_almacenar.setText("Almacenar");
        jbtn_almacenar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_almacenar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_almacenar.setPreferredSize(new java.awt.Dimension(300, 40));

        jbtn_modificar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_modificar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_modificar.setText("Modificar");
        jbtn_modificar.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtn_modificar.setMinimumSize(new java.awt.Dimension(200, 40));
        jbtn_modificar.setPreferredSize(new java.awt.Dimension(200, 40));

        jbtn_eliminar.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_eliminar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.setMaximumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setMinimumSize(new java.awt.Dimension(300, 40));
        jbtn_eliminar.setPreferredSize(new java.awt.Dimension(300, 40));

        jbtn_nuevo.setBackground(new java.awt.Color(0, 51, 51));
        jbtn_nuevo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jbtn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_nuevo.setText("Nuevo");
        jbtn_nuevo.setMaximumSize(new java.awt.Dimension(884, 40));
        jbtn_nuevo.setMinimumSize(new java.awt.Dimension(884, 40));
        jbtn_nuevo.setPreferredSize(new java.awt.Dimension(884, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(jlb_encabezado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlb_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlb_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlb_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlb_encabezado)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jlb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jlb_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jlb_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jlb_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_almacenar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jlb_direccion;
    public javax.swing.JLabel jlb_email;
    public javax.swing.JLabel jlb_encabezado;
    public javax.swing.JLabel jlb_id;
    public javax.swing.JLabel jlb_nombre;
    public javax.swing.JLabel jlb_telefono;
    public javax.swing.JTextField jtf_direccion;
    public javax.swing.JTextField jtf_email;
    public javax.swing.JTextField jtf_id;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
